import type { FAQPage, HowTo, SoftwareApplication, WithContext } from "schema-dts";
import type { ToolLocaleContent } from "../../../types";
import { bibliography } from "../bibliography";
import type { AbvDilutionCalculatorUI } from "../ui";

const slug = "calculateur-dilution-alcool-et-proof";
const title = "Calculateur de dilution d'alcool et de proof";
const description = "Calculez la quantité d'eau à ajouter pour réduire le degré d'un spiritueux. Le calculateur affiche le volume final, l'alcool pur et le ratio de dilution.";
const ui: AbvDilutionCalculatorUI = {
  unitLabel: "Unités de volume", metricUnit: "Métrique ml", imperialUnit: "Impérial fl oz", strengthLabel: "Unités de degré", abvUnit: "Pourcentage d'alcool", proofUnit: "Proof américain", presetLabel: "Scénarios rapides", spiritPresetLabel: "Spiritueux de 750 ml", liqueurPresetLabel: "Liqueur de 700 ml", cocktailPresetLabel: "Lot de 500 ml", startingStrengthLabel: "Degré initial", startingVolumeLabel: "Volume initial", targetStrengthLabel: "Degré cible", waterToAddLabel: "Eau à ajouter", finalVolumeLabel: "Volume final", pureAlcoholLabel: "Alcool pur", ratioLabel: "Ratio d'eau", startingProofLabel: "Proof initial", targetProofLabel: "Proof cible", readyMessage: "Votre cible est plus basse. Mesurez l'eau puis mélangez progressivement.", invalidMessage: "La cible doit être inférieure au degré initial pour une dilution.", largeAdditionMessage: "Ce lot demande au moins autant d'eau que de spiritueux. Mélangez par étapes et vérifiez à nouveau.", bottleLabel: "Bouteille graduée indiquant le volume final calculé", waterLayerLabel: "Couche d'eau dans le mélange final", estimateNotice: "Estimation de préparation uniquement. L'alcool et l'eau peuvent se contracter après mélange ; vérifiez le degré final avec un matériel adapté.", sourceLabel: "Sources de la formule", calculateAction: "Paramètres de dilution", resetAction: "Réinitialiser les valeurs", volumeHint: "Choisissez le volume disponible avant d'ajouter l'eau.", strengthHint: "Le proof est affiché selon le système américain: 80 proof correspondent à 40 pour cent d'alcool.",
};
const faq = [
  { question: "Comment calculer l'eau nécessaire pour diluer l'alcool ?", answer: "Multipliez d'abord le volume initial par le degré initial afin d'obtenir le volume d'alcool pur. Divisez ce volume par le degré cible écrit en décimal pour obtenir le volume final théorique. Soustrayez le volume initial pour trouver l'eau à ajouter." },
  { question: "Quelle est la différence entre ABV et proof ?", answer: "Le pourcentage volumique indique la part d'alcool pur dans le liquide. Dans le système américain, le proof vaut deux fois le pourcentage: 80 proof équivalent à 40 pour cent. Le sélecteur modifie l'affichage sans modifier la concentration réelle." },
  { question: "Le calculateur tient-il compte de la contraction de l'alcool et de l'eau ?", answer: "Non. Le résultat est une estimation fondée sur la conservation de l'alcool pur. L'éthanol et l'eau peuvent occuper un volume combiné légèrement inférieur après mélange, et la température modifie aussi le volume. Utilisez le résultat comme plan puis vérifiez avec un alcoomètre adapté." },
  { question: "Puis-je l'utiliser pour fabriquer une boisson alcoolisée légale ?", answer: "Cet outil fait uniquement de l'arithmétique et ne vérifie ni la recette, ni l'étiquetage, ni les droits d'accise, ni les licences, ni les règles locales. Respectez les obligations du lieu de fabrication et de vente et utilisez un matériel propre." },
];
const howTo = [
  { name: "Choisir les unités de volume", text: "Sélectionnez les millilitres métriques ou les onces liquides impériales. Le volume physique reste identique lorsque vous changez d'unité." },
  { name: "Saisir le lot initial", text: "Indiquez le degré initial et le volume de spiritueux disponible avant la dilution." },
  { name: "Définir le degré cible", text: "Saisissez un degré inférieur pour le mélange final. Les cibles qui ne sont pas des dilutions sont signalées." },
  { name: "Ajouter l'eau par étapes", text: "Lisez les volumes d'eau et de mélange, incorporez progressivement puis vérifiez le degré final avec un équipement adapté." },
];
const faqSchema: WithContext<FAQPage> = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: howTo.map((step, index) => ({ "@type": "HowToStep", position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: title, description, applicationCategory: "UtilitiesApplication", operatingSystem: "All", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, inLanguage: "fr" };
export const content: ToolLocaleContent<AbvDilutionCalculatorUI> = { slug, title, description, ui, faqTitle: "Questions sur la dilution", bibliographyTitle: "Sources de la formule", faq, howTo, schemas: [faqSchema, howToSchema, appSchema], bibliography, seo: [
  { type: "title", text: "Comment fonctionne la dilution d'alcool", level: 2 },
  { type: "paragraph", html: "La dilution réduit la concentration alcoolique en ajoutant de l'eau, tout en conservant approximativement la quantité d'alcool pur. Ce <strong>calculateur de dilution d'alcool</strong> transforme un degré et un volume de départ en quantité d'eau utile et en volume final théorique. Il fonctionne localement dans le navigateur, sans envoyer les données du lot." },
  { type: "table", headers: ["Valeur", "Formule", "Signification"], rows: [["Alcool pur", "volume initial x degré initial", "Alcool conservé dans le mélange"], ["Volume final", "alcool pur / degré cible", "Total théorique après dilution"], ["Eau à ajouter", "volume final moins volume initial", "Quantité d'eau à prévoir"]] },
  { type: "title", text: "Conversion entre ABV et proof", level: 2 },
  { type: "paragraph", html: "Le pourcentage volumique exprime la part d'alcool pur dans le liquide. Dans le système américain, le proof correspond au double du pourcentage: 40 pour cent d'alcool équivalent à 80 proof. Utilisez le sélecteur lorsqu'une étiquette indique un proof, en gardant à l'esprit que les conventions varient selon les pays et les périodes." },
  { type: "stats", columns: 3, items: [{ value: "80 proof", label: "40 pour cent d'alcool" }, { value: "1:1", label: "Ratio d'eau du scénario par défaut" }, { value: "100% local", label: "Aucune donnée de lot envoyée" }] },
  { type: "title", text: "Pourquoi le résultat reste une estimation", level: 2 },
  { type: "paragraph", html: "Le calcul conserve le volume d'alcool pur, mais les mélanges réels ne sont pas parfaitement additifs. L'alcool et l'eau se contractent en se combinant ; la température modifie également la densité et le volume mesuré. Ajoutez l'eau lentement, attendez la température de mesure souhaitée et vérifiez le degré avec un matériel adapté." },
  { type: "tip", title: "Mélanger progressivement et vérifier", html: "Employez une eau propre et mesurée dans un récipient assez grand pour le volume final théorique. Le calculateur ne connaît ni la température, ni le sucre, ni les arômes, ni les règles locales. Considérez le résultat comme un plan de départ, et non comme une certification du degré final." },
  { type: "title", text: "Une méthode de dilution reproductible", level: 2 },
  { type: "list", items: ["Notez le degré indiqué et le volume réel du lot.", "Choisissez un degré cible inférieur au degré initial.", "Calculez l'alcool pur, le volume final et l'eau.", "Ajoutez la majeure partie de l'eau, mélangez puis complétez par petites quantités.", "Vérifiez le mélange à la température prévue pour la mesure."] },
  { type: "diagnostic", variant: "warning", title: "Un calcul n'est pas une autorisation de production", html: "Cette page ne valide ni les ingrédients, ni l'hygiène, ni l'étiquetage, ni les taxes, ni les licences, ni la vente. N'utilisez jamais un résultat numérique pour ignorer les règles applicables à votre boisson ou à votre lieu." },
] };
